api_port: "_env:API_PORT:8080"
postgres_user: "_env:POSTGRES_USER:api"
postgres_password: "_env:POSTGRES_PASSWORD:passwd"
postgres_host: "_env:POSTGRES_HOST:'127.0.0.1'"
postgres_database: "_env:POSTGRES_DATABASE:'nuitomo-api'"
postgres_port: "_env:POSTGRES_PORT:'5432'"
elasticsearch_url: "_env:ELASTICSEARCH_HOST:'http://localhost:9200'"
deploy_env: "_env:DEPLOY_ENV:'Development'"
deploy_cors_origins: "_env:DEPLOY_CORS_ORIGINS:[]"
db_pool_stripe_num: "_env:DB_POOL_STRIPE_NUM:1"
db_pool_resource_num: "_env:DB_POOL_RESOURCE_NUM:20"
db_pool_keep_time: "_env:DB_POOL_KEEP_TIME:60"
log_level: "_env:LOG_LEVEL:'Debug'"
api_secret_key: "_env:API_SECRET_KEY:'dummy'"
